### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by xiaoyuMo** [brucexx/heisenberg#12]
common.log

**Comment by xiaoyuMo** [comment]
java.lang.ArrayIndexOutOfBoundsException: 224
	at com.baidu.hsb.mysql.CharsetUtil.getCharset(CharsetUtil.java:122)
	at com.baidu.hsb.mysql.nio.MySQLConnectionAuthenticator.handle(MySQLConnectionAuthenticator.java:46)
	at com.baidu.hsb.net.BackendConnection.handle(BackendConnection.java:114)
	at com.baidu.hsb.net.AbstractConnection.read(AbstractConnection.java:180)
	at com.baidu.hsb.net.NIOReactor$R.read(NIOReactor.java:120)
	at com.baidu.hsb.net.NIOReactor$R.run(NIOReactor.java:88)
	at java.lang.Thread.run(Thread.java:748)
